Change JavaScript MIME type
WebOfTrust/keripy pull request #316
Opened 2022-09-26 18:46 UTC by euj1n0ng

A minor fix for successful testing.

`text/javascript` is a recommended standard (both by IETF and by MDN). `application/javascript` is obsolete.

2022-09-28 01:26 UTC, pfeairheller requested changes
This change will break this test as it's testing the return from the HTTP request.  

If you want to change the MIME type of the actual request you'll have to update Hio, I believe

2022-09-28 08:24 UTC, euj1n0ng commented
> This change will break this test as it's testing the return from the HTTP request.
> 
> If you want to change the MIME type of the actual request you'll have to update Hio, I believe


Yeah, you are right. At a glance, `falcon` still uses `application/javascript` for the JS MIME type in the simulation of HTTP request. However, surprisingly, on Ubuntu machine the test was failed on the stale MIME type while there was no problem on a Mac machine.
![image](https://user-images.githubusercontent.com/62314480/192727389-46f34c06-9ddd-4eb8-abe5-ce5379b3c6e5.png)

If you want, I'll close this PR. Of course, you can directly close it.

2022-09-28 09:04 UTC, euj1n0ng commented
https://github.com/falconry/falcon/issues/2110

2022-09-28 17:51 UTC, pfeairheller commented
So we can close this issue here I assume?

2022-09-28 17:53 UTC, euj1n0ng commented
Yes.

2022-09-28 17:53 UTC, closed without merging

2023-06-03 09:51 UTC, vytas7 commented
Hello @euj1n0ng & @pfeairheller!
While we are looking to enforce Falcon's standard media types for some common file types, you can absolutely override this in your application if you wish.

Just add the desired types to your application's [`app.resp_options`](https://falcon.readthedocs.io/en/stable/api/app.html#falcon.App.resp_options), for instance,
```python
app.resp_options.static_media_types['.js'] = 'text/javascript'
```

2024-10-23 13:33 UTC, vytas7 commented
**Update**: you should now get @euj1n0ng's improvement automatically via Falcon 4.0.0+.